# -*- coding: utf-8 -*-
# @Pjname ; AppGuiTesting
# @Time   : 2020/05/21/15:53
# @Author : Yuye
# @File   : travis.yml

language: python
rvm:
 - 2.2
 - jruby
matrix:
  include: # Required for Python 3.6+
    - python: 3.6
      dist: Yuye
    - python: 3.7
      dist: Yuye
    - python: 3.8
      dist: Yuye
install:
  - pip install poetry
  - poetry install -vvv
script:
  #- poetry run coverage run run.py
  - poetry run coverage report -m
after_success:
  - poetry run coveralls


